# Generated by Django 4.2.11 on 2024-03-13 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_alter_tovar_author_alter_tovar_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tovars_categories', to='main.categories'),
            preserve_default=False,
        ),
    ]
