# Generated by Django 5.0.2 on 2024-03-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_tovar_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovar',
            name='author',
        ),
    ]
