# Generated by Django 5.0.2 on 2024-03-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_tovar_tovarimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='tovarimage',
            field=models.ImageField(default=None, upload_to='img/tovarimages', verbose_name='Фото товара'),
        ),
    ]
