# Generated by Django 5.0.2 on 2024-03-27 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_tovar_tovarimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovar',
            name='tovarimage',
        ),
    ]
